using System;
using System.Drawing;
using System.Windows.Forms;

partial class ServerForm {
    TableLayoutPanel layout,header,headText,settingsGrid,portBox,keyBox,actionGrid,stateGrid,stateText,addressGrid,addressHeader,footer,footerInfo,updateBox;
    CardPanel settings,actions,stateCard,addressCard;
    NumericUpDown port;
    TextBox key;
    ModernButton start,stop,open,hide,show,update,firewallAllow;
    UiLabel status,statusTitle;
    Label versionLabel;
    UiLabel firewallStatus;
    CheckBox notifyUpdates;
    TableLayoutPanel addressRows;
    StatusBadge badge;
    StatusDot statusDot;
    NotifyIcon tray;
    System.Windows.Forms.Timer timer;

    void InitializeComponent() {
        SuspendLayout();
        port=new NumericUpDown();key=new TextBox();start=new ModernButton();stop=new ModernButton();open=new ModernButton();hide=new ModernButton();show=new ModernButton();update=new ModernButton();firewallAllow=new ModernButton();firewallStatus=new UiLabel();notifyUpdates=new CheckBox();
        status=new UiLabel();statusTitle=new UiLabel();addressRows=new TableLayoutPanel();badge=new StatusBadge();statusDot=new StatusDot();tray=new NotifyIcon();timer=new System.Windows.Forms.Timer();
        Text="Rabbit 인증 서버 "+BuildInfo.Version+" · Windows";ClientSize=new Size(920,900);MinimumSize=new Size(820,860);Font=new Font("맑은 고딕",9);StartPosition=FormStartPosition.CenterScreen;BackColor=UiPalette.Canvas;AutoScaleDimensions=new SizeF(96F,96F);AutoScaleMode=AutoScaleMode.Dpi;

        layout=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=UiPalette.Canvas,Padding=new Padding(28,12,28,18),ColumnCount=1,RowCount=6};
        layout.RowStyles.Add(new RowStyle(SizeType.Absolute,118));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,184));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,88));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,136));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,70));Controls.Add(layout);

        header=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,BackColor=UiPalette.Canvas,Margin=new Padding(0)};header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,118));header.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,122));
        header.Controls.Add(new RabbitMark{Anchor=AnchorStyles.Left|AnchorStyles.Top},0,0);headText=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=UiPalette.Canvas,RowCount=2,Margin=new Padding(0)};headText.RowStyles.Add(new RowStyle(SizeType.Absolute,48));headText.RowStyles.Add(new RowStyle(SizeType.Percent,100));headText.Controls.Add(new UiLabel{Text="Rabbit 인증 서버",ForeColor=UiPalette.Text,Font=new Font("맑은 고딕",21,FontStyle.Bold),AutoSize=false,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft},0,0);headText.Controls.Add(new UiLabel{Text="Windows · 이미지 주소만 전달 · 동시 인증 2개",ForeColor=UiPalette.Muted,AutoSize=false,Dock=DockStyle.Fill,TextAlign=ContentAlignment.TopLeft,AutoEllipsis=true},0,1);header.Controls.Add(headText,1,0);badge.Anchor=AnchorStyles.Top|AnchorStyles.Right;badge.Margin=new Padding(0,8,0,0);header.Controls.Add(badge,2,0);layout.Controls.Add(header,0,0);

        settings=new CardPanel{Dock=DockStyle.Fill,Padding=new Padding(22,12,22,10),Margin=new Padding(0,0,0,12)};settingsGrid=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=Color.White,ColumnCount=2,RowCount=3};settingsGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,36));settingsGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,64));settingsGrid.RowStyles.Add(new RowStyle(SizeType.Absolute,32));settingsGrid.RowStyles.Add(new RowStyle(SizeType.Absolute,72));settingsGrid.RowStyles.Add(new RowStyle(SizeType.Percent,100));var settingsTitle=new UiLabel{Text="연결 설정",ForeColor=UiPalette.Text,Font=new Font("맑은 고딕",12,FontStyle.Bold),AutoSize=false,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft};settingsGrid.Controls.Add(settingsTitle,0,0);settingsGrid.SetColumnSpan(settingsTitle,2);
        portBox=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=Color.White,ColumnCount=1,RowCount=2,Margin=new Padding(0,0,24,0)};portBox.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));portBox.RowStyles.Add(new RowStyle(SizeType.Absolute,27));portBox.RowStyles.Add(new RowStyle(SizeType.Absolute,41));portBox.Controls.Add(new UiLabel{Text="접속 포트",ForeColor=UiPalette.Muted,AutoSize=false,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft},0,0);port.Minimum=1024;port.Maximum=65535;port.Value=9870;port.AutoSize=false;port.Dock=DockStyle.Fill;port.Margin=new Padding(0);port.MinimumSize=new Size(0,38);port.BackColor=Color.White;port.ForeColor=UiPalette.Text;port.Font=new Font("Segoe UI",11);port.BorderStyle=BorderStyle.FixedSingle;portBox.Controls.Add(port,0,1);settingsGrid.Controls.Add(portBox,0,1);
        keyBox=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=Color.White,RowCount=2,ColumnCount=2,Margin=new Padding(0)};keyBox.RowStyles.Add(new RowStyle(SizeType.Absolute,27));keyBox.RowStyles.Add(new RowStyle(SizeType.Absolute,41));keyBox.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));keyBox.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,82));var keyLabel=new UiLabel{Text="접속 키",ForeColor=UiPalette.Muted,AutoSize=false,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft};keyBox.Controls.Add(keyLabel,0,0);keyBox.SetColumnSpan(keyLabel,2);key.Dock=DockStyle.Fill;key.UseSystemPasswordChar=true;key.MaxLength=128;key.Font=new Font("Segoe UI",11);key.BorderStyle=BorderStyle.FixedSingle;keyBox.Controls.Add(key,0,1);show.Text="보기";show.Dock=DockStyle.Fill;show.Margin=new Padding(10,0,0,0);show.Click+=ShowKey_Click;keyBox.Controls.Add(show,1,1);settingsGrid.Controls.Add(keyBox,1,1);
        var helper=new UiLabel{Text="숫자·영문·기호 4자 이상 · NAS 비밀번호는 사용하지 마세요",ForeColor=UiPalette.Muted,AutoSize=false,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft,AutoEllipsis=true,Margin=new Padding(0,4,0,0)};settingsGrid.Controls.Add(helper,0,2);settingsGrid.SetColumnSpan(helper,2);settings.Controls.Add(settingsGrid);layout.Controls.Add(settings,0,1);

        actions=new CardPanel{Dock=DockStyle.Fill,Padding=new Padding(14,8,14,8),Margin=new Padding(0,0,0,12)};actionGrid=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=Color.White,ColumnCount=4};actionGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,25));actionGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,25));actionGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,25));actionGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,25));start.Text="▶  서버 시작";start.SetPrimary();start.Dock=DockStyle.Fill;start.Margin=new Padding(0,0,8,0);start.Click+=Start_Click;actionGrid.Controls.Add(start,0,0);stop.Text="■  서버 중지";stop.Dock=DockStyle.Fill;stop.Margin=new Padding(0,0,8,0);stop.Enabled=false;stop.Click+=Stop_Click;actionGrid.Controls.Add(stop,1,0);open.Text="▣  관리 화면";open.Dock=DockStyle.Fill;open.Margin=new Padding(0,0,8,0);open.Enabled=false;open.Click+=Open_Click;actionGrid.Controls.Add(open,2,0);hide.Text="⇩  트레이로 숨기기";hide.Dock=DockStyle.Fill;hide.TextColor=UiPalette.Primary;hide.OutlineColor=Color.White;hide.Click+=HideToTray_Click;actionGrid.Controls.Add(hide,3,0);actions.Controls.Add(actionGrid);layout.Controls.Add(actions,0,2);

        stateCard=new CardPanel{Dock=DockStyle.Fill,SurfaceColor=Color.FromArgb(255,252,244),BorderColor=Color.FromArgb(244,211,142),Padding=new Padding(20,16,20,16),Margin=new Padding(0,0,0,12)};stateGrid=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=stateCard.SurfaceColor,ColumnCount=2};stateGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,68));stateGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));statusDot.Anchor=AnchorStyles.Left|AnchorStyles.Top;stateGrid.Controls.Add(statusDot,0,0);stateText=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=stateCard.SurfaceColor,RowCount=2,Margin=new Padding(0)};stateText.RowStyles.Add(new RowStyle(SizeType.Absolute,40));stateText.RowStyles.Add(new RowStyle(SizeType.Percent,100));statusTitle.Text="서버가 중지되어 있습니다";statusTitle.ForeColor=UiPalette.Text;statusTitle.Font=new Font("맑은 고딕",13,FontStyle.Bold);statusTitle.AutoSize=false;statusTitle.Dock=DockStyle.Fill;statusTitle.TextAlign=ContentAlignment.MiddleLeft;statusTitle.AutoEllipsis=true;stateText.Controls.Add(statusTitle,0,0);status.Text="접속 키를 확인한 뒤 서버를 시작하세요.";status.ForeColor=UiPalette.Muted;status.AutoSize=false;status.Dock=DockStyle.Fill;status.TextAlign=ContentAlignment.TopLeft;status.AutoEllipsis=true;stateText.Controls.Add(status,0,1);stateGrid.Controls.Add(stateText,1,0);stateCard.Controls.Add(stateGrid);layout.Controls.Add(stateCard,0,3);

        addressCard=new CardPanel{Dock=DockStyle.Fill,Margin=new Padding(0,0,0,12)};addressGrid=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=Color.White,RowCount=3};addressGrid.RowStyles.Add(new RowStyle(SizeType.Absolute,46));addressGrid.RowStyles.Add(new RowStyle(SizeType.Percent,100));addressGrid.RowStyles.Add(new RowStyle(SizeType.Absolute,32));
        addressHeader=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=Color.White,ColumnCount=3,RowCount=1,Margin=new Padding(0)};addressHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));addressHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,164));addressHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,126));addressHeader.Controls.Add(new UiLabel{Text="확장앱에 입력할 서버 주소",ForeColor=UiPalette.Text,Font=new Font("맑은 고딕",12,FontStyle.Bold),AutoSize=false,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft,AutoEllipsis=true},0,0);firewallStatus.Text="방화벽 확인 중…";firewallStatus.ForeColor=UiPalette.Muted;firewallStatus.AutoSize=false;firewallStatus.Dock=DockStyle.Fill;firewallStatus.TextAlign=ContentAlignment.MiddleRight;firewallStatus.AutoEllipsis=true;addressHeader.Controls.Add(firewallStatus,1,0);firewallAllow.Text="방화벽 허용";firewallAllow.Dock=DockStyle.Fill;firewallAllow.Margin=new Padding(10,3,0,3);firewallAllow.Click+=FirewallAllow_Click;addressHeader.Controls.Add(firewallAllow,2,0);addressGrid.Controls.Add(addressHeader,0,0);
        addressRows.Dock=DockStyle.Fill;addressRows.BackColor=UiPalette.Border;addressRows.ColumnCount=1;addressRows.RowCount=1;addressRows.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));addressRows.RowStyles.Add(new RowStyle(SizeType.Percent,100));addressRows.CellBorderStyle=TableLayoutPanelCellBorderStyle.Single;addressGrid.Controls.Add(addressRows,0,1);addressGrid.Controls.Add(new UiLabel{Text="주소를 더블클릭해도 복사할 수 있습니다",ForeColor=UiPalette.Muted,AutoSize=false,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft,Margin=new Padding(0,6,0,0)},0,2);addressCard.Controls.Add(addressGrid);layout.Controls.Add(addressCard,0,4);

        footer=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=UiPalette.Canvas,ColumnCount=3,RowCount=1,Margin=new Padding(0)};footer.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,36));footer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));footer.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,136));footer.RowStyles.Add(new RowStyle(SizeType.Percent,100));footer.Controls.Add(new FooterShield{Anchor=AnchorStyles.Left|AnchorStyles.Top,Margin=new Padding(0,14,0,0)},0,0);footerInfo=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=UiPalette.Canvas,ColumnCount=1,RowCount=2,Margin=new Padding(0)};footerInfo.RowStyles.Add(new RowStyle(SizeType.Absolute,31));footerInfo.RowStyles.Add(new RowStyle(SizeType.Percent,100));notifyUpdates.Text="새 버전 자동 알림";notifyUpdates.Checked=true;notifyUpdates.ForeColor=UiPalette.Text;notifyUpdates.AutoSize=true;notifyUpdates.Anchor=AnchorStyles.Left|AnchorStyles.Bottom;notifyUpdates.CheckedChanged+=NotifyUpdates_CheckedChanged;footerInfo.Controls.Add(notifyUpdates,0,0);footerInfo.Controls.Add(new UiLabel{Text="브라우저 로그인 · 사용자 lab / 위 접속 키",ForeColor=UiPalette.Muted,AutoSize=false,Dock=DockStyle.Fill,TextAlign=ContentAlignment.TopLeft,AutoEllipsis=true},0,1);footer.Controls.Add(footerInfo,1,0);
        updateBox=new TableLayoutPanel{Dock=DockStyle.Fill,BackColor=UiPalette.Canvas,ColumnCount=1,RowCount=2,Margin=new Padding(0)};updateBox.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));updateBox.RowStyles.Add(new RowStyle(SizeType.Absolute,27));updateBox.RowStyles.Add(new RowStyle(SizeType.Absolute,36));versionLabel=new Label{Text="v"+BuildInfo.Version,ForeColor=UiPalette.Muted,BackColor=UiPalette.Canvas,AutoSize=false,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleRight,Font=new Font("Segoe UI",9,FontStyle.Bold),Margin=new Padding(0)};updateBox.Controls.Add(versionLabel,0,0);update.Text="업데이트 확인";update.Dock=DockStyle.Fill;update.Margin=new Padding(0,1,0,0);update.Font=new Font("맑은 고딕",8,FontStyle.Bold);update.Click+=Update_Click;updateBox.Controls.Add(update,0,1);footer.Controls.Add(updateBox,2,0);layout.Controls.Add(footer,0,5);

        AcceptButton=start;ResumeLayout(true);
    }
}
